<a href="https://colab.research.google.com/github/econ105/ttest/blob/main/Matricies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Create a column matrix
column_matrix = np.array([[1], [2], [3]])
print("Column matrix:")
print(column_matrix)

# Create a row matrix
row_matrix = np.array([[1, 2, 3]])
print("Row matrix:")
print(row_matrix)

Column matrix:
[[1]
 [2]
 [3]]
Row matrix:
[[1 2 3]]


In [2]:
import numpy as np

# Create a 2x4 matrix
matrix_2x4 = np.array([[1, 2, 3, 4],
                       [5, 6, 7, 8]])
print("2x4 matrix:")
print(matrix_2x4)

# Create a 3x5 matrix
matrix_3x5 = np.array([[1, 2, 3, 4, 5],
                       [6, 7, 8, 9, 10],
                       [11, 12, 13, 14, 15]])
print("3x5 matrix:")
print(matrix_3x5)

2x4 matrix:
[[1 2 3 4]
 [5 6 7 8]]
3x5 matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [5]:
import numpy as np

# Create the first 3x5 matrix
matrix1 = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

# Create the second 3x5 matrix
matrix2 = np.array([[5, 4, 3, 2, 1],
                    [10, 9, 8, 7, 6],
                    [15, 14, 13, 12, 11]])

# Add the matrices
result = matrix1 + matrix2

# Print the result
print("Matrix Addition:")
print(result)

Matrix Addition:
[[ 6  6  6  6  6]
 [16 16 16 16 16]
 [26 26 26 26 26]]


In [6]:
import numpy as np

# Create the first 3x5 matrix
matrix1 = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

# Create the second 3x5 matrix
matrix2 = np.array([[5, 4, 3, 2, 1],
                    [10, 9, 8, 7, 6],
                    [15, 14, 13, 12, 11]])

# Subtract the matrices
result = matrix1 - matrix2

# Print the result
print("Matrix Subtraction:")
print(result)

Matrix Subtraction:
[[-4 -2  0  2  4]
 [-4 -2  0  2  4]
 [-4 -2  0  2  4]]


In [ ]:
import numpy as np

# Create the first 3x5 matrix
matrix1 = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15]])

# Create the second 3x5 matrix
matrix2 = np.array([[5, 4, 3, 2, 1],
                    [10, 9, 8, 7, 6],
                    [15, 14, 13, 12, 11]])

# Multiply the matrices
result = matrix1 * matrix2

# Print the result
print("Matrix Multiplication:")
print(result)

In [ ]:
import numpy as np

# Create the first matrix
matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Create the second matrix
matrix2 = np.array([[2, 2, 2],
                    [2, 2, 2],
                    [2, 2, 2]])

# Divide the matrices element-wise
result = matrix1 / matrix2

# Print the result
print("Matrix Division:")
print(result)
# What is the use of matrix? That is related to linear algebra which is the basic of many modelling.
# Further reading: https://realpython.com/python-linear-algebra/